### ISSUE TITLE
Release as npm package

### ISSUE THREAD

**Issue by armenzg** [mozilla-frontend-infra/perf-goggles-demo#2]
By doing so we will be able to use on projects like firefox-health-dashboard (a forked version is landed there) and the js-perf-dashboard.

@csd713 is interested on working on this.

**Comment by csd713** [comment]
@armenzg as discussed on IRC, I have published a temporary npm package for this project. This can be used until the official package is published.
https://www.npmjs.com/package/perf-goggles-temp

**Comment by armenzg** [comment]
Thank you!
Do you have a PR for the code changes for this?
I assume we will need a change like [this](https://github.com/taskcluster/taskcluster-client-web/blob/master/package.json#L8-L11) to make sure that *only* the code from the library is published rather than the React components (under src/).

**Comment by csd713** [comment]
I only renamed the project name in `package.json` file. And below is the list of files included in the package.
```
npm notice 📦  perf-goggles-temp@1.0.0
npm notice === Tarball Contents === 
npm notice 816B    package.json                  
npm notice 117B    .eslintrc.js                  
npm notice 1.6kB   .neutrinorc.js                
npm notice 16.7kB  LICENSE                       
npm notice 134B    netlify.toml                  
npm notice 203B    README.md                     
npm notice 305.6kB yarn.lock                     
npm notice 26B     src/App.css                   
npm notice 793B    src/App.jsx                   
npm notice 392B    src/components/graph.jsx      
npm notice 1.1kB   src/components/list_suites.jsx
npm notice 2.2kB   src/containers/perfherder.jsx 
npm notice 463B    src/index.jsx                 
npm notice 3.6kB   src/utils/perfherder.js
```

Since the project is renamed and is temporary, it will create discrepancies if I send a PR.
Would you still recommend a PR with the changes you have mentioned?

**Comment by armenzg** [comment]
I've spoken with a co-worker of mine and we believe the best way to do this is to start from scratch.
I've renamed this repository as [perf-goggles-demo](url) and created the same [repo](https://github.com/mozilla-frontend-infra/perf-goggles) again.

Can you clone that and use neutrino's wizard and choose the "library" preset?
https://neutrinojs.org/installation/create-new-project.html

I will file the two issues on that repo.

**Comment by armenzg** [comment]
https://github.com/mozilla-frontend-infra/perf-goggles/issues/1
